name: secrets_box
description: "SecretsBox mobile app with Redux."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: 2.0.5
  objectbox: 2.5.0
  objectbox_flutter_libs: 2.5.0
  crypto: 3.0.3
  uuid: 4.3.3
  get_it: 7.6.7
  path: 1.9.0
  path_provider: 2.1.2
  intl: 0.18.1
  go_router: 13.2.1
  rxdart: 0.27.7
  redux: 5.0.0
  flutter_redux: 0.10.0
  redux_epics: 0.15.1
  redux_logging: 0.5.1
  built_collection: 5.1.1
  built_value: 8.8.1
  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.8
  mocktail: 1.0.3
  objectbox_generator: 2.5.0
  go_router_builder: 2.4.1
  built_value_generator: 8.8.1
  freezed: 2.4.6

flutter:
  uses-material-design: true

flutter_intl:
  main_locale: en
  enabled: true
  arb_dir: res/l10n